parameters:
    uam.cookie_consent.renderer.class: UAM\CookieConsent\CookieConsentBundle\Renderer\DefaultRenderer

services:
    uam.cookie_consent.renderer:
        class: %uam.cookie_consent.renderer.class%
        arguments:
            - "@service_container"
        public: false

    uam.cookie_consent.twig.extension:
        class: UAM\CookieConsent\CookieConsentBundle\Twig\Extension\CookieConsentExtension
        arguments: ["@uam.cookie_consent.renderer"]
        tags:
            - { name: twig.extension }
